/* Generated By:JavaCC: Do not edit this line. StormFrontProtocolParserConstants.java */
package cc.warlock.core.stormfront.internal;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface StormFrontProtocolParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TAG_START_OPEN = 1;
  /** RegularExpression Id. */
  int TAG_END_OPEN = 2;
  /** RegularExpression Id. */
  int ENTITY = 3;
  /** RegularExpression Id. */
  int PCDATA = 4;
  /** RegularExpression Id. */
  int NAMECHAR = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int BELL = 8;
  /** RegularExpression Id. */
  int TAG_CLOSE = 9;
  /** RegularExpression Id. */
  int TAG_EMPTY_CLOSE = 10;
  /** RegularExpression Id. */
  int ATTR_EQ = 11;
  /** RegularExpression Id. */
  int ATTR_VALUE = 12;
  /** RegularExpression Id. */
  int GENERIC_ID = 13;
  /** RegularExpression Id. */
  int WS = 14;
  /** RegularExpression Id. */
  int PASS_STRING = 16;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_TAG_MODE = 1;
  /** Lexical state. */
  int PASS_THRU = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"<\"",
    "\"</\"",
    "<ENTITY>",
    "<PCDATA>",
    "<NAMECHAR>",
    "<DIGIT>",
    "<LETTER>",
    "\"\\u0007\"",
    "\">\"",
    "\"/>\"",
    "\"=\"",
    "<ATTR_VALUE>",
    "<GENERIC_ID>",
    "<WS>",
    "\"<mode\"",
    "<PASS_STRING>",
  };

}
